# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhche
type: Opaque
data:
  CHE_FABRIC8_ANALYTICS_SEGMENT__WRITE__KEY: 'NULL'
  CHE_FABRIC8_ANALYTICS_WOOPRA__DOMAIN: 'NULL'
  CHE_FABRIC8_END2END_PROTECT_VERIFY__WITH__IP: "false"
  CHE_API: "https://che.prod-preview.openshift.io/api"
  CHE_CORS_ENABLED: "true"
  CHE_FABRIC8_AUTH_ENDPOINT: "https://auth.prod-preview.openshift.io"
  CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL: "https://osoproxy.prod-preview.openshift.io"
  CHE_FABRIC8_MULTITENANT: "true"
  CHE_FABRIC8_USER__SERVICE_ENDPOINT: "https://api.prod-preview.openshift.io/api/user/services"
  CHE_HOST: "che.prod-preview.openshift.io"
  CHE_KEYCLOAK_AUTH__SERVER__URL: "NULL"
  CHE_KEYCLOAK_CLIENT__ID: "740650a2-9c44-4db5-b067-a3d1b2cd2d01"
  CHE_KEYCLOAK_JS__ADAPTER__URL: "/api/fabric8-end2end/files/RhCheKeycloak.js"
  CHE_KEYCLOAK_OIDC__PROVIDER: "https://auth.prod-preview.openshift.io/api"
  CHE_KEYCLOAK_REALM: "NULL"
  CHE_KEYCLOAK_USE__NONCE: "false"
  CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
  CHE_LOGS_DIR: "/data/logs"
  SENTRY_DSN: 'NULL'
  CHE_LOGS_SENTRY_LEVEL: 'WARN'
  CHE_METRICS_ENABLED: "false"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "true"
  CHE_INFRA_OPENSHIFT_TLS__ENABLED: "true"
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "true"
  JAVA_OPTS: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=25 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.net.preferIPv4Stack=true"
  CHE_SYSTEM_ADMIN__NAME: "admin"
  CHE_SYSTEM_SUPER__PRIVILEGED__MODE: "true"
  CHE_WEBSOCKET_ENDPOINT: "wss://che.prod-preview.openshift.io/api/websocket"
  CHE_WEBSOCKET_ENDPOINT__MINOR: "wss://che.prod-preview.openshift.io/api/websocket-minor"
  CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS: "-XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom -Djava.net.preferIPv4Stack=true"
  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: "900000"
  CHE_WORKSPACE_LOGS_ROOT__DIR: "/workspace_logs"
  CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS: "500"
  CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD: "1"
  CHE_WORKSPACE_JAVA__OPTIONS: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m -Djava.net.preferIPv4Stack=true"
  CHE_WORKSPACE_AUTO__START: "true"
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: "https://che.prod-preview.openshift.io/agent-binaries/linux_amd64/bootstrapper/bootstrapper"
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "common"
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "true"
  CHE_INFRA_KUBERNETES_RUNTIMES__CONSISTENCY__CHECK__PERIOD__MIN: "30"
  CHE_KEYCLOAK_GITHUB_ENDPOINT: "https://auth.prod-preview.openshift.io/api/token?for=https://github.com"
  CHE_LOCAL_CONF_DIR: "/etc/conf"
  CHE_LOG_LEVEL: "INFO"
  CHE_LOGS_APPENDERS_IMPL: "json"
  CHE_MULTIUSER: "true"
  CHE_WORKSPACE_PLUGIN__REGISTRY__URL: 'https://che-plugin-registry.prod-preview.openshift.io/'
  CHE_PORT: "8080"
  CHE_DEBUG_SERVER: "false"
  SENTRY_ENVIRONMENT: 'dev'
  SENTRY_STACKTRACE_APP_PACKAGES: 'com.redhat,org.eclipse.che'
  CHE_WORKSPACE_DEFAULT__MEMORY__MB: "3000"
  CHE_LIMITS_WORKSPACE_ENV_RAM: "3gb"
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: '1Gi'
  CHE_SERVER_SECURE__EXPOSER_JWTPROXY_MEMORY__LIMIT: "150mb"
  CHE_WORKSPACE_SIDECAR_DEFAULT__MEMORY__LIMIT__MB: "150"
  CHE_INFRA_KUBERNETES_SERVICE__ACCOUNT__NAME: "che-workspace"
  CHE_WORKSPACE_STORAGE: "/home/user/che/workspaces"
  CHE_FABRIC8_CDN_PREFETCH_EDITOR: 'NULL'
  che.core.jsonrpc.processor.major.max.pool.size: 120
  che.core.jsonrpc.processor.major.queue.capacity: 40000
